kind: DataGrid
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: compositions-page-datagrid
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  apiRef:
    name: compositions-panels
    namespace: {{ .Release.Namespace }}
  widgetData:
    prefix: compositions-datagrid-filters
    asGrid: true
    grid:
      column: 1
    items: []
  widgetDataTemplate:
    - forPath: items
      expression: >
        ${ [ .compositionspanels[] | { resourceRefId: .metadata.name } ] }
  resourcesRefs: 
    items: []
  resourcesRefsTemplate:
    - iterator: ${ .compositionspanels }
      template:
        id: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: panels
        namespace: ${ .metadata.namespace }
        name: ${ .metadata.name }
        verb: GET