kind: NavMenuItem
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: nav-menu-item-compositions
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
      - pages
    resourceRefId: compositions-page
    label: Compositions
    icon: fa-shapes
    path: /compositions
    order: 30
  resourcesRefs:
    items:
      - id: compositions-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: compositions-page
        namespace: {{ .Release.Namespace }}
        resource: pages
        verb: GET