kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: blueprints-page
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
      - buttons
      - datagrids
    items:
      - resourceRefId: blueprints-page-button-drawer-filters
      - resourceRefId: blueprints-page-datagrid
  resourcesRefs:
    items:
      - id: blueprints-page-button-drawer-filters
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: blueprints-page-button-drawer-filters
        namespace: {{ .Release.Namespace }}
        resource: buttons
        verb: GET
      - id: blueprints-page-datagrid
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: blueprints-page-datagrid
        namespace: {{ .Release.Namespace }}
        resource: datagrids
        verb: GET
        slice:
          page: 1
          perPage: 5