apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: compositions-list
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: list
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=composition.krateo.io&namespace=*&raw=true&limit=5000"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: list
  filter: |
    {
      list: ([ .list | .items[] | .raw ])
    }