apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: blueprints-list
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: list
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=core.krateo.io&resource=compositiondefinitions&limit=5000&namespace=*&raw=true"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: listError
    filter: |
      [ .list | .items[] | .raw ]

