apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: compositions-list
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: list
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: ${ if .slice.cursor != "" then ("/resources?group=composition.krateo.io&limit=" + .slice.perPage + "&namespace=*&raw=true&cursor=" + .slice.cursor) else ("/resources?group=composition.krateo.io&limit=" + .slice.perPage + "&namespace=*&raw=true") end }
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: list
  filter: |
    {
      list: ([ .list | .items[] | .raw ]),
      slice: {
        cursor: .list.cursor,
        perPage: .slice.perPage,
      }
    }