apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: blueprints-list
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - filter: '[.namespaces.items[] | .metadata.name]'
    name: namespaces
    path: /api/v1/namespaces
  - continueOnError: true
    dependsOn:
      iterator: .namespaces
      name: namespaces
    name: allCompositionDefinitions
    path: ${ "/apis/core.krateo.io/v1alpha1/namespaces/" + (.) + "/compositiondefinitions"}
  filter: >
    {
      list: (
        if (.allCompositionDefinitions | type) == "array" then
          [.allCompositionDefinitions[]?.items[]?]
        elif (.allCompositionDefinitions | type) == "object" then
          [.allCompositionDefinitions.items[]?]
        else
          []
        end
      )
    }


