apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: sidebar-nav-menu-items
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: navmenuitems
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=widgets.templates.krateo.io&version=v1beta1&resource=navmenuitems&limit=5000&namespace=*&raw=true"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: navmenuitemsError
    filter: |
      [ .navmenuitems | .items[] | .raw ]
