apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: blueprints-panels
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: blueprintspanels
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: ${ if .slice.cursor != "" then ("/resources?group=widgets.templates.krateo.io&resource=panels&version=v1beta1&namespace=*&limit=" + (.slice.perPage | tostring) + "&raw=true&cursor=" + .slice.cursor) else ("/resources?group=widgets.templates.krateo.io&resource=panels&version=v1beta1&namespace=*&limit=" + (.slice.perPage | tostring) + "&raw=true") end }
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: blueprintspanelsError
  filter: >
    ([ .blueprintspanels.items[] | .raw ]) as $panels |
    {
      blueprintspanels: [$panels[]? | select((.metadata.labels // {})["krateo.io/portal-page"] == "blueprints")],
      slice: {
        cursor: .blueprintspanels.cursor,
        perPage: .slice.perPage
      }
    }

