apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: compositions-panels
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: compositionspanels
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: >
      ${ 
        if .slice.cursor? != "" then 
          ( "/resources?group=widgets.templates.krateo.io&resource=panels&version=v1beta1&namespace=*&limit=" + (.slice.perPage | tostring) + "&raw=true&cursor=" + .slice.cursor ) 
        elif (.slice.perPage? != "" and .slice.perPage? != "NULL") then
          ( "/resources?group=widgets.templates.krateo.io&resource=panels&version=v1beta1&namespace=*&limit=" + (.slice.perPage | tostring) + "&raw=true" ) 
        else 
          ( "/resources?group=widgets.templates.krateo.io&resource=panels&version=v1beta1&namespace=*&limit=5000&raw=true" ) 
        end
      }
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: allCompositionsError
  filter: >
    ([ .compositionspanels.items[] | .raw ]) as $panels |
    {
      compositionspanels: [$panels[]? | select((.metadata.labels // {})["krateo.io/portal-page"] == "compositions")],
      slice: {
        cursor: .compositionspanels.cursor,
        perPage: .slice.perPage
      },
      sliceold: .slice
    }