apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: all-routes
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  api:
  - name: routes
    endpointRef:
      name: resources-presenter-endpoint
      namespace: krateo-system
    path: "/resources?group=widgets.templates.krateo.io&version=v1beta1&resource=routes&limit=10000&namespace=*&raw=true"
    verb: GET 
    continueOnError: true
    exportJwt: true
    errorKey: routes
    filter: |
      [ .routes | .items[] | .raw ]
