{{- if .Values.enableDemoSystemNamespace }}
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Route
metadata:
  name: demo-system-2-composition-route
  namespace: demo-system-2
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    path: /compositions/demo-system-2/{kind}/{name}
    resourceRefId: demo-system-2-composition-tablist
  resourcesRefs:
    items:
      - id: demo-system-2-composition-tablist
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: "{kind}-{name}-composition-tablist"
        namespace: demo-system-2
        resource: tablists
        verb: GET
{{- end }}