{{- if .Values.enableDemoSystemNamespace }}
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Route
metadata:
  name: demo-system-compositions-route
  namespace: demo-system
spec:
  widgetData:
    path: /compositions/demo-system
    resourceRefId: demo-system-compositions-page-datagrid
  resourcesRefs:
    items:
      - id: demo-system-compositions-page-datagrid
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: demo-system-compositions-page-datagrid
        namespace: demo-system
        resource: datagrids
        verb: GET
{{- end }}