{{- if .Values.enableDemoSystemNamespace }}
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Route
metadata:
  name: demo-system-composition-route
  namespace: demo-system
spec:
  widgetData:
    path: /compositions/demo-system/{name}
    resourceRefId: demo-system-composition-tablist
  resourcesRefs:
    items:
      - id: demo-system-composition-tablist
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: "{name}-composition-tablist"
        namespace: demo-system
        resource: tablists
        verb: GET
{{- end }}