{{- if .Values.enableDemoSystemNamespace }}
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Route
metadata:
  name: demo-system-composition-route
  namespace: demo-system
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    path: /compositions/{namespace}/{kind}/{name}
    resourceRefId: composition-tablist
  resourcesRefs:
    items:
      - id: composition-tablist
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: "{kind}-{name}-composition-tablist"
        namespace: "{namespace}"
        resource: tablists
        verb: GET
{{- end }}