kind: RoutesLoader
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: routes-loader
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  widgetData:
    allowedResources:
      - routes
  resourcesRefs: 
    items: []
  resourcesRefsTemplate:
    - iterator: ${ .routes }
      template:
        id: ${ .metadata.namespace + "_" + .metadata.name }
        name: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: routes
        namespace: ${ .metadata.namespace }
        verb: GET
  apiRef:
    name: all-routes
    namespace: {{ .Release.Namespace }}