kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: blueprints-row
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/verbose": "true"
spec:
  apiRef:
    name: blueprints-panels
    namespace: {{ .Release.Namespace }}
  widgetData:
    allowedResources:
      - panels
    items: []
  widgetDataTemplate:
    - forPath: items
      expression: >
        ${ [ .blueprintspanels[] | { resourceRefId: .metadata.name, size: 12 } ] }
  resourcesRefs: 
    items: []
  resourcesRefsTemplate:
    - iterator: ${ .blueprintspanels }
      template:
        id: ${ .metadata.name }
        apiVersion: ${ .apiVersion }
        resource: panels
        namespace: ${ .metadata.namespace }
        name: ${ .metadata.name }
        verb: GET
